export interface LeagueTeam {
  name: string;
  logo: string;
  points: number;
  wins: number;
  draws: number;
  losses: number;
  goalsFor: number;
  goalsAgainst: number;
  played: number;
  strength?: number;
}

const emptyStats = { points: 0, wins: 0, draws: 0, losses: 0, goalsFor: 0, goalsAgainst: 0, played: 0 };

export const countryNames: Record<string, string> = {
  BR: 'Brasil',
  AR: 'Argentina',
  ES: 'Espanha',
  FR: 'França',
  IT: 'Itália',
  DE: 'Alemanha',
  EN: 'Inglaterra',
  PT: 'Portugal',
  NL: 'Holanda',
  MX: 'México',
  CO: 'Colômbia',
  JP: 'Japão',
};

export const countryFlags: Record<string, string> = {
  BR: '🇧🇷', AR: '🇦🇷', ES: '🇪🇸', FR: '🇫🇷', IT: '🇮🇹', DE: '🇩🇪',
  EN: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', PT: '🇵🇹', NL: '🇳🇱', MX: '🇲🇽', CO: '🇨🇴', JP: '🇯🇵',
};

export const countryLeagueNames: Record<string, string> = {
  BR: 'Brasileirão Série A',
  AR: 'Liga Profesional',
  ES: 'La Liga',
  FR: 'Ligue 1',
  IT: 'Serie A',
  DE: 'Bundesliga',
  EN: 'Premier League',
  PT: 'Liga Portugal',
  NL: 'Eredivisie',
  MX: 'Liga MX',
  CO: 'Liga BetPlay',
  JP: 'J1 League',
};

export const leaguesByCountry: Record<string, LeagueTeam[]> = {
  BR: [
    { name: 'Flamengo SC', logo: '🔴', ...emptyStats, strength: 86 },
    { name: 'Palmeiras FC', logo: '🌴', ...emptyStats, strength: 84 },
    { name: 'Atlético MG', logo: '🐓', ...emptyStats, strength: 80 },
    { name: 'Corinthians SP', logo: '🦅', ...emptyStats, strength: 78 },
    { name: 'São Paulo EC', logo: '🏟️', ...emptyStats, strength: 77 },
    { name: 'Internacional RS', logo: '🔴', ...emptyStats, strength: 76 },
    { name: 'Grêmio RS', logo: '⚡', ...emptyStats, strength: 75 },
    { name: 'Botafogo RJ', logo: '⭐', ...emptyStats, strength: 74 },
    { name: 'Fluminense RJ', logo: '🟢', ...emptyStats, strength: 73 },
    { name: 'Santos FC', logo: '🐟', ...emptyStats, strength: 72 },
    { name: 'Cruzeiro MG', logo: '🌟', ...emptyStats, strength: 71 },
    { name: 'Bahia EC', logo: '🔵', ...emptyStats, strength: 69 },
    { name: 'Fortaleza EC', logo: '🦁', ...emptyStats, strength: 70 },
    { name: 'Vasco da Gama', logo: '⚓', ...emptyStats, strength: 68 },
    { name: 'Athletico PR', logo: '🔴', ...emptyStats, strength: 67 },
    { name: 'Bragantino SP', logo: '🐂', ...emptyStats, strength: 66 },
    { name: 'Cuiabá EC', logo: '🟡', ...emptyStats, strength: 62 },
    { name: 'Goiás EC', logo: '🟢', ...emptyStats, strength: 61 },
    { name: 'Coritiba FC', logo: '🟢', ...emptyStats, strength: 60 },
  ],
  AR: [
    { name: 'Boca Juniors', logo: '🟡', ...emptyStats, strength: 84 },
    { name: 'River Plate', logo: '🔴', ...emptyStats, strength: 83 },
    { name: 'Racing Club', logo: '🏁', ...emptyStats, strength: 76 },
    { name: 'Independiente', logo: '👑', ...emptyStats, strength: 74 },
    { name: 'San Lorenzo', logo: '🔵', ...emptyStats, strength: 72 },
    { name: 'Vélez Sarsfield', logo: '⚪', ...emptyStats, strength: 71 },
    { name: 'Estudiantes LP', logo: '📚', ...emptyStats, strength: 73 },
    { name: "Newell's Old Boys", logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Rosario Central', logo: '🟡', ...emptyStats, strength: 68 },
    { name: 'Argentinos Juniors', logo: '🔴', ...emptyStats, strength: 67 },
    { name: 'Defensa y Justicia', logo: '🟢', ...emptyStats, strength: 70 },
    { name: 'Lanús', logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Talleres Córdoba', logo: '🔵', ...emptyStats, strength: 71 },
    { name: 'Godoy Cruz', logo: '⚪', ...emptyStats, strength: 66 },
    { name: 'Banfield', logo: '🟢', ...emptyStats, strength: 65 },
    { name: 'Colón Santa Fe', logo: '🔴', ...emptyStats, strength: 64 },
    { name: 'Unión Santa Fe', logo: '🔴', ...emptyStats, strength: 63 },
    { name: 'Huracán', logo: '⚪', ...emptyStats, strength: 66 },
    { name: 'Central Córdoba', logo: '⚫', ...emptyStats, strength: 61 },
  ],
  ES: [
    { name: 'Real Madrid CF', logo: '👑', ...emptyStats, strength: 93 },
    { name: 'FC Barcelona', logo: '🔵', ...emptyStats, strength: 91 },
    { name: 'Atlético Madrid', logo: '🔴', ...emptyStats, strength: 83 },
    { name: 'Sevilla FC', logo: '⚪', ...emptyStats, strength: 77 },
    { name: 'Real Betis', logo: '🟢', ...emptyStats, strength: 75 },
    { name: 'Real Sociedad', logo: '🔵', ...emptyStats, strength: 76 },
    { name: 'Valencia CF', logo: '🦇', ...emptyStats, strength: 73 },
    { name: 'Villarreal CF', logo: '🟡', ...emptyStats, strength: 75 },
    { name: 'Athletic Bilbao', logo: '🦁', ...emptyStats, strength: 74 },
    { name: 'Celta de Vigo', logo: '🔵', ...emptyStats, strength: 69 },
    { name: 'Osasuna', logo: '🔴', ...emptyStats, strength: 68 },
    { name: 'Getafe CF', logo: '🔵', ...emptyStats, strength: 67 },
    { name: 'Girona FC', logo: '🔴', ...emptyStats, strength: 72 },
    { name: 'Rayo Vallecano', logo: '⚡', ...emptyStats, strength: 66 },
    { name: 'Mallorca', logo: '🔴', ...emptyStats, strength: 65 },
    { name: 'Espanyol', logo: '🔵', ...emptyStats, strength: 64 },
    { name: 'Alavés', logo: '🔵', ...emptyStats, strength: 62 },
    { name: 'Las Palmas', logo: '🟡', ...emptyStats, strength: 63 },
    { name: 'Cádiz CF', logo: '🟡', ...emptyStats, strength: 61 },
  ],
  FR: [
    { name: 'Paris SG', logo: '🗼', ...emptyStats, strength: 91 },
    { name: 'Olympique Marseille', logo: '🔵', ...emptyStats, strength: 79 },
    { name: 'Olympique Lyon', logo: '🦁', ...emptyStats, strength: 77 },
    { name: 'AS Monaco', logo: '🔴', ...emptyStats, strength: 78 },
    { name: 'LOSC Lille', logo: '🐕', ...emptyStats, strength: 75 },
    { name: 'Stade Rennais', logo: '🔴', ...emptyStats, strength: 72 },
    { name: 'OGC Nice', logo: '🌴', ...emptyStats, strength: 73 },
    { name: 'RC Lens', logo: '🟡', ...emptyStats, strength: 74 },
    { name: 'FC Nantes', logo: '🟢', ...emptyStats, strength: 68 },
    { name: 'RC Strasbourg', logo: '🔵', ...emptyStats, strength: 67 },
    { name: 'Montpellier HSC', logo: '🔵', ...emptyStats, strength: 66 },
    { name: 'Stade Brestois', logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Toulouse FC', logo: '🟣', ...emptyStats, strength: 67 },
    { name: 'Reims', logo: '🔴', ...emptyStats, strength: 65 },
    { name: 'Le Havre AC', logo: '🔵', ...emptyStats, strength: 63 },
    { name: 'FC Lorient', logo: '🟠', ...emptyStats, strength: 62 },
    { name: 'FC Metz', logo: '🔴', ...emptyStats, strength: 61 },
    { name: 'Clermont Foot', logo: '🔴', ...emptyStats, strength: 60 },
    { name: 'AJ Auxerre', logo: '🔵', ...emptyStats, strength: 60 },
  ],
  IT: [
    { name: 'Inter Milan', logo: '🔵', ...emptyStats, strength: 86 },
    { name: 'AC Milan', logo: '🔴', ...emptyStats, strength: 83 },
    { name: 'Juventus FC', logo: '⚫', ...emptyStats, strength: 84 },
    { name: 'SSC Napoli', logo: '🔵', ...emptyStats, strength: 81 },
    { name: 'Atalanta BC', logo: '🔵', ...emptyStats, strength: 79 },
    { name: 'AS Roma', logo: '🐺', ...emptyStats, strength: 77 },
    { name: 'SS Lazio', logo: '🦅', ...emptyStats, strength: 75 },
    { name: 'ACF Fiorentina', logo: '🟣', ...emptyStats, strength: 74 },
    { name: 'Torino FC', logo: '🐂', ...emptyStats, strength: 69 },
    { name: 'Bologna FC', logo: '🔴', ...emptyStats, strength: 72 },
    { name: 'Udinese', logo: '⚫', ...emptyStats, strength: 67 },
    { name: 'Sassuolo', logo: '🟢', ...emptyStats, strength: 66 },
    { name: 'Monza', logo: '🔴', ...emptyStats, strength: 65 },
    { name: 'Empoli FC', logo: '🔵', ...emptyStats, strength: 64 },
    { name: 'Cagliari', logo: '🔴', ...emptyStats, strength: 63 },
    { name: 'Lecce', logo: '🟡', ...emptyStats, strength: 62 },
    { name: 'Genoa CFC', logo: '🔴', ...emptyStats, strength: 64 },
    { name: 'Hellas Verona', logo: '🟡', ...emptyStats, strength: 61 },
    { name: 'Frosinone', logo: '🟡', ...emptyStats, strength: 60 },
  ],
  DE: [
    { name: 'Bayern München', logo: '🔴', ...emptyStats, strength: 91 },
    { name: 'Borussia Dortmund', logo: '🟡', ...emptyStats, strength: 83 },
    { name: 'Bayer Leverkusen', logo: '⚫', ...emptyStats, strength: 82 },
    { name: 'RB Leipzig', logo: '🔴', ...emptyStats, strength: 79 },
    { name: 'VfB Stuttgart', logo: '🔴', ...emptyStats, strength: 74 },
    { name: 'Eintracht Frankfurt', logo: '🦅', ...emptyStats, strength: 75 },
    { name: 'VfL Wolfsburg', logo: '🐺', ...emptyStats, strength: 72 },
    { name: 'SC Freiburg', logo: '🔴', ...emptyStats, strength: 71 },
    { name: "Borussia M'gladbach", logo: '🟢', ...emptyStats, strength: 70 },
    { name: 'Union Berlin', logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Hoffenheim', logo: '🔵', ...emptyStats, strength: 68 },
    { name: 'Werder Bremen', logo: '🟢', ...emptyStats, strength: 67 },
    { name: 'Mainz 05', logo: '🔴', ...emptyStats, strength: 66 },
    { name: 'FC Augsburg', logo: '🔴', ...emptyStats, strength: 64 },
    { name: 'FC Köln', logo: '⚪', ...emptyStats, strength: 65 },
    { name: 'Bochum', logo: '🔵', ...emptyStats, strength: 62 },
    { name: 'Heidenheim', logo: '🔴', ...emptyStats, strength: 61 },
    { name: 'Darmstadt 98', logo: '🔵', ...emptyStats, strength: 60 },
    { name: 'Holstein Kiel', logo: '🔵', ...emptyStats, strength: 59 },
  ],
  EN: [
    { name: 'Manchester City', logo: '🔵', ...emptyStats, strength: 92 },
    { name: 'Arsenal FC', logo: '🔴', ...emptyStats, strength: 89 },
    { name: 'Liverpool FC', logo: '🔴', ...emptyStats, strength: 88 },
    { name: 'Chelsea FC', logo: '🔵', ...emptyStats, strength: 81 },
    { name: 'Manchester United', logo: '🔴', ...emptyStats, strength: 79 },
    { name: 'Tottenham', logo: '⚪', ...emptyStats, strength: 77 },
    { name: 'Newcastle United', logo: '⚫', ...emptyStats, strength: 78 },
    { name: 'Aston Villa', logo: '🟣', ...emptyStats, strength: 76 },
    { name: 'West Ham United', logo: '🔨', ...emptyStats, strength: 73 },
    { name: 'Brighton', logo: '🔵', ...emptyStats, strength: 74 },
    { name: 'Crystal Palace', logo: '🦅', ...emptyStats, strength: 69 },
    { name: 'Wolverhampton', logo: '🟠', ...emptyStats, strength: 70 },
    { name: 'Fulham FC', logo: '⚪', ...emptyStats, strength: 68 },
    { name: 'Brentford FC', logo: '🐝', ...emptyStats, strength: 69 },
    { name: 'Nottingham Forest', logo: '🌳', ...emptyStats, strength: 67 },
    { name: 'Everton FC', logo: '🔵', ...emptyStats, strength: 66 },
    { name: 'Bournemouth', logo: '🍒', ...emptyStats, strength: 67 },
    { name: 'Burnley FC', logo: '🔴', ...emptyStats, strength: 62 },
    { name: 'Sheffield United', logo: '🔴', ...emptyStats, strength: 61 },
  ],
  PT: [
    { name: 'SL Benfica', logo: '🦅', ...emptyStats, strength: 83 },
    { name: 'FC Porto', logo: '🐉', ...emptyStats, strength: 82 },
    { name: 'Sporting CP', logo: '🦁', ...emptyStats, strength: 81 },
    { name: 'SC Braga', logo: '🔴', ...emptyStats, strength: 73 },
    { name: 'Vitória SC', logo: '⚪', ...emptyStats, strength: 68 },
    { name: 'Rio Ave FC', logo: '🟢', ...emptyStats, strength: 65 },
    { name: 'Gil Vicente FC', logo: '🔴', ...emptyStats, strength: 63 },
    { name: 'Boavista FC', logo: '⚫', ...emptyStats, strength: 64 },
    { name: 'Marítimo FC', logo: '🟢', ...emptyStats, strength: 62 },
    { name: 'Famalicão', logo: '🔵', ...emptyStats, strength: 66 },
    { name: 'Casa Pia AC', logo: '🟢', ...emptyStats, strength: 64 },
    { name: 'Arouca FC', logo: '🟡', ...emptyStats, strength: 61 },
    { name: 'Estoril Praia', logo: '🟡', ...emptyStats, strength: 62 },
    { name: 'Moreirense FC', logo: '🟢', ...emptyStats, strength: 63 },
    { name: 'Portimonense', logo: '⚫', ...emptyStats, strength: 60 },
    { name: 'Vizela FC', logo: '🔵', ...emptyStats, strength: 59 },
    { name: 'Chaves', logo: '🔴', ...emptyStats, strength: 58 },
    { name: 'Estrela Amadora', logo: '⭐', ...emptyStats, strength: 60 },
    { name: 'Farense', logo: '⚪', ...emptyStats, strength: 57 },
  ],
  NL: [
    { name: 'Ajax Amsterdam', logo: '🔴', ...emptyStats, strength: 81 },
    { name: 'PSV Eindhoven', logo: '🔴', ...emptyStats, strength: 80 },
    { name: 'Feyenoord', logo: '🔴', ...emptyStats, strength: 78 },
    { name: 'AZ Alkmaar', logo: '🔴', ...emptyStats, strength: 73 },
    { name: 'FC Twente', logo: '🔴', ...emptyStats, strength: 71 },
    { name: 'FC Utrecht', logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Vitesse', logo: '🟡', ...emptyStats, strength: 67 },
    { name: 'SC Heerenveen', logo: '🔵', ...emptyStats, strength: 65 },
    { name: 'FC Groningen', logo: '🟢', ...emptyStats, strength: 64 },
    { name: 'Sparta Rotterdam', logo: '🔴', ...emptyStats, strength: 66 },
    { name: 'NEC Nijmegen', logo: '🔴', ...emptyStats, strength: 65 },
    { name: 'Go Ahead Eagles', logo: '🦅', ...emptyStats, strength: 63 },
    { name: 'Fortuna Sittard', logo: '🟡', ...emptyStats, strength: 62 },
    { name: 'RKC Waalwijk', logo: '🟡', ...emptyStats, strength: 60 },
    { name: 'PEC Zwolle', logo: '🔵', ...emptyStats, strength: 61 },
    { name: 'Excelsior', logo: '🔴', ...emptyStats, strength: 59 },
    { name: 'Heracles Almelo', logo: '⚫', ...emptyStats, strength: 62 },
    { name: 'Cambuur Leeuwarden', logo: '🔵', ...emptyStats, strength: 58 },
    { name: 'Volendam', logo: '🟠', ...emptyStats, strength: 57 },
  ],
  MX: [
    { name: 'Club América', logo: '🦅', ...emptyStats, strength: 82 },
    { name: 'Chivas Guadalajara', logo: '🔴', ...emptyStats, strength: 79 },
    { name: 'Tigres UANL', logo: '🐯', ...emptyStats, strength: 80 },
    { name: 'CF Monterrey', logo: '🔵', ...emptyStats, strength: 78 },
    { name: 'Cruz Azul', logo: '🔵', ...emptyStats, strength: 77 },
    { name: 'UNAM Pumas', logo: '🐆', ...emptyStats, strength: 73 },
    { name: 'Santos Laguna', logo: '🟢', ...emptyStats, strength: 72 },
    { name: 'León FC', logo: '🟢', ...emptyStats, strength: 71 },
    { name: 'Toluca FC', logo: '🔴', ...emptyStats, strength: 70 },
    { name: 'Pachuca CF', logo: '🔵', ...emptyStats, strength: 74 },
    { name: 'Atlas FC', logo: '🔴', ...emptyStats, strength: 69 },
    { name: 'Puebla FC', logo: '🔵', ...emptyStats, strength: 66 },
    { name: 'Querétaro FC', logo: '🔵', ...emptyStats, strength: 64 },
    { name: 'Necaxa', logo: '🔴', ...emptyStats, strength: 65 },
    { name: 'Mazatlán FC', logo: '🟣', ...emptyStats, strength: 63 },
    { name: 'FC Juárez', logo: '🟢', ...emptyStats, strength: 62 },
    { name: 'Tijuana', logo: '🔴', ...emptyStats, strength: 67 },
    { name: 'San Luis', logo: '🔴', ...emptyStats, strength: 64 },
    { name: 'Tampico Madero', logo: '🔵', ...emptyStats, strength: 60 },
  ],
  CO: [
    { name: 'Atlético Nacional', logo: '🟢', ...emptyStats, strength: 79 },
    { name: 'Millonarios FC', logo: '🔵', ...emptyStats, strength: 77 },
    { name: 'América de Cali', logo: '🔴', ...emptyStats, strength: 75 },
    { name: 'Deportivo Cali', logo: '🟢', ...emptyStats, strength: 73 },
    { name: 'Junior Barranquilla', logo: '🔴', ...emptyStats, strength: 74 },
    { name: 'Independiente Medellín', logo: '🔴', ...emptyStats, strength: 72 },
    { name: 'Santa Fe', logo: '🔴', ...emptyStats, strength: 71 },
    { name: 'Once Caldas', logo: '⚪', ...emptyStats, strength: 68 },
    { name: 'Deportes Tolima', logo: '🟡', ...emptyStats, strength: 70 },
    { name: 'Bucaramanga', logo: '🟡', ...emptyStats, strength: 67 },
    { name: 'Envigado FC', logo: '🟠', ...emptyStats, strength: 65 },
    { name: 'Águilas Doradas', logo: '🦅', ...emptyStats, strength: 64 },
    { name: 'La Equidad', logo: '🟢', ...emptyStats, strength: 66 },
    { name: 'Pasto', logo: '🔴', ...emptyStats, strength: 63 },
    { name: 'Pereira FC', logo: '🔴', ...emptyStats, strength: 64 },
    { name: 'Patriotas FC', logo: '🔴', ...emptyStats, strength: 61 },
    { name: 'Jaguares Córdoba', logo: '🐆', ...emptyStats, strength: 60 },
    { name: 'Alianza Petrolera', logo: '🟡', ...emptyStats, strength: 62 },
    { name: 'Boyacá Chicó', logo: '🟢', ...emptyStats, strength: 59 },
  ],
  JP: [
    { name: 'Vissel Kobe', logo: '🔴', ...emptyStats, strength: 77 },
    { name: 'Yokohama F. Marinos', logo: '🔵', ...emptyStats, strength: 76 },
    { name: 'Kawasaki Frontale', logo: '🔵', ...emptyStats, strength: 75 },
    { name: 'Urawa Red Diamonds', logo: '🔴', ...emptyStats, strength: 74 },
    { name: 'Kashima Antlers', logo: '🦌', ...emptyStats, strength: 73 },
    { name: 'FC Tokyo', logo: '🔵', ...emptyStats, strength: 71 },
    { name: 'Gamba Osaka', logo: '🔵', ...emptyStats, strength: 70 },
    { name: 'Nagoya Grampus', logo: '🐬', ...emptyStats, strength: 69 },
    { name: 'Cerezo Osaka', logo: '🌸', ...emptyStats, strength: 68 },
    { name: 'Sanfrecce Hiroshima', logo: '🟣', ...emptyStats, strength: 72 },
    { name: 'Sagan Tosu', logo: '🔵', ...emptyStats, strength: 65 },
    { name: 'Consadole Sapporo', logo: '🔴', ...emptyStats, strength: 66 },
    { name: 'Avispa Fukuoka', logo: '🟢', ...emptyStats, strength: 64 },
    { name: 'Kashiwa Reysol', logo: '🟡', ...emptyStats, strength: 67 },
    { name: 'Shimizu S-Pulse', logo: '🟠', ...emptyStats, strength: 63 },
    { name: 'Júbilo Iwata', logo: '🔵', ...emptyStats, strength: 62 },
    { name: 'Albirex Niigata', logo: '🟠', ...emptyStats, strength: 64 },
    { name: 'Kyoto Sanga', logo: '🟣', ...emptyStats, strength: 63 },
    { name: 'Shonan Bellmare', logo: '🟢', ...emptyStats, strength: 61 },
  ],
};

export function getLeagueTeams(country: string, clubName: string): LeagueTeam[] {
  const teams = leaguesByCountry[country] || leaguesByCountry['BR'];
  const playerTeam: LeagueTeam = { name: clubName, logo: '⚽', ...emptyStats, strength: 60 };
  return [playerTeam, ...teams];
}

// Keep backward compatibility
export const initialLeagueTeams = leaguesByCountry['BR'].map(t => ({ ...t }));
initialLeagueTeams.unshift({ name: 'FLM 26', logo: '⚽', ...emptyStats });
